-- Startivo Seed Data — 15 realistic Polish sports events 2026
-- Run: psql $DATABASE_URL -f server/db/seed.sql

INSERT INTO events (name, slug, sport_type, date_start, date_end, city, voivodeship, description, distance, difficulty, max_participants, price, registration_url, registration_deadline, organizer_name, organizer_email, event_website, status, featured, lat, lng) VALUES

(
  'Runmageddon Warszawa 2026',
  'runmageddon-warszawa-2026',
  'ocr',
  '2026-05-16',
  '2026-05-17',
  'Warszawa',
  'mazowieckie',
  'Największy bieg z przeszkodami w Polsce powraca do stolicy! Pokonaj 12 km trasy pełnej błota, wody i 30 unikalnych przeszkód. Runmageddon Warszawa to połączenie siły, wytrzymałości i dobrej zabawy. Czy jesteś gotowy na wyzwanie, które zmieni twoje postrzeganie własnych możliwości?',
  '12 km / 30 przeszkód',
  'hard',
  5000,
  199,
  'https://runmageddon.pl/rejestracja',
  '2026-05-10',
  'Runmageddon Sp. z o.o.',
  'info@runmageddon.pl',
  'https://runmageddon.pl',
  'published',
  true,
  52.2297,
  21.0122
),

(
  'Runmageddon Kraków 2026',
  'runmageddon-krakow-2026',
  'ocr',
  '2026-06-13',
  '2026-06-14',
  'Kraków',
  'małopolskie',
  'Runmageddon Kraków to legendarny bieg z przeszkodami w malowniczej scenerii Małopolski. 10 km trasy z 25 przeszkodami zaprojektowanymi tak, by sprawdzić każdy aspekt twojej sprawności fizycznej. Błoto, zimna woda, ściany do wspinaczki — to dopiero rozgrzewka!',
  '10 km / 25 przeszkód',
  'hard',
  3500,
  189,
  'https://runmageddon.pl/krakow',
  '2026-06-08',
  'Runmageddon Sp. z o.o.',
  'info@runmageddon.pl',
  'https://runmageddon.pl',
  'published',
  false,
  50.0647,
  19.9450
),

(
  'Runmageddon Wrocław 2026',
  'runmageddon-wroclaw-2026',
  'ocr',
  '2026-07-04',
  '2026-07-05',
  'Wrocław',
  'dolnośląskie',
  'Runmageddon we Wrocławiu — kolejna edycja kultowego biegu z przeszkodami na Dolnym Śląsku. 15 km ekstremalnej trasy, ponad 35 przeszkód i niezapomniane emocje. Kategorie: Classic (5 km), Rekrut (3 km) i Open (15 km). Każdy znajdzie coś dla siebie!',
  '5–15 km / 20–35 przeszkód',
  'hard',
  4000,
  209,
  'https://runmageddon.pl/wroclaw',
  '2026-06-28',
  'Runmageddon Sp. z o.o.',
  'info@runmageddon.pl',
  'https://runmageddon.pl',
  'published',
  true,
  51.1079,
  17.0385
),

(
  'HYROX Gdańsk 2026',
  'hyrox-gdansk-2026',
  'hyrox',
  '2026-04-25',
  '2026-04-26',
  'Gdańsk',
  'pomorskie',
  'HYROX to globalny fitness racing — połączenie biegu i ćwiczeń funkcjonalnych. W Gdańsku zawodnicy pokonają 8× 1 km biegu przeplatane 8 stacjami fitness: SkiErg, Sandbag Lunges, Wall Balls, Burpee Broad Jumps i więcej. Format: Singles, Doubles i Relay.',
  '8 km biegu + 8 stacji fitness',
  'hard',
  2000,
  399,
  'https://hyrox.com/gdansk',
  '2026-04-18',
  'HYROX GmbH',
  'info@hyrox.com',
  'https://hyrox.com',
  'published',
  true,
  54.3520,
  18.6466
),

(
  'HYROX Poznań 2026',
  'hyrox-poznan-2026',
  'hyrox',
  '2026-09-19',
  '2026-09-20',
  'Poznań',
  'wielkopolskie',
  'HYROX Poznań — jedyne takie zawody fitness racing w Wielkopolsce! Sprawdź się w globalnym formacie: 8 km biegu + 8 stacji funkcjonalnych. MTP Poznań zamienia się w arenę, gdzie liczy się zarówno kondycja biegowa, jak i siła mięśniowa.',
  '8 km biegu + 8 stacji fitness',
  'hard',
  2500,
  419,
  'https://hyrox.com/poznan',
  '2026-09-12',
  'HYROX GmbH',
  'info@hyrox.com',
  'https://hyrox.com',
  'published',
  false,
  52.4064,
  16.9252
),

(
  'Triathlon Gdynia 2026',
  'triathlon-gdynia-2026',
  'triathlon',
  '2026-08-15',
  '2026-08-16',
  'Gdynia',
  'pomorskie',
  'Triathlon Gdynia — prestiżowe zawody triathlonowe nad Bałtykiem. Dystanse: Sprint (750m/20km/5km), Olimpijski (1500m/40km/10km) oraz Half-Ironman (1900m/90km/21km). Pływanie w Zatoce Gdańskiej, jazda rowerem wzdłuż Trójmiejskiego Parku Krajobrazowego i bieg nadmorskim bulwarem.',
  '750m–1900m pływanie / 20–90km rower / 5–21km bieg',
  'extreme',
  1500,
  299,
  'https://triathlongdynia.pl',
  '2026-08-01',
  'Triathlon Poland Sp. z o.o.',
  'start@triathlongdynia.pl',
  'https://triathlongdynia.pl',
  'published',
  true,
  54.5189,
  18.5305
),

(
  'Triathlon Olsztyn 2026',
  'triathlon-olsztyn-2026',
  'triathlon',
  '2026-07-19',
  '2026-07-19',
  'Olsztyn',
  'warmińsko-mazurskie',
  'Triathlon na jeziorach Warmii i Mazur — niezapomniane doświadczenie w sercu Krainy Tysiąca Jezior. Pływanie w krystalicznie czystym Jeziorze Ukiel, rower po malowniczych drogach Warmii i bieg po lesie dookoła jeziora. Trasa olimpijska i sprint dla wszystkich poziomów.',
  '750m–1500m pływanie / 20–40km rower / 5–10km bieg',
  'extreme',
  800,
  279,
  'https://triathlonolsztyn.pl',
  '2026-07-05',
  'Mazurski Klub Triathlonu',
  'kontakt@triathlonolsztyn.pl',
  'https://triathlonolsztyn.pl',
  'published',
  false,
  53.7784,
  20.4801
),

(
  'PKO Bieg Papieski Wadowice 2026',
  'bieg-papieski-wadowice-2026',
  'running',
  '2026-04-18',
  '2026-04-18',
  'Wadowice',
  'małopolskie',
  'Bieg upamiętniający urodziny Karola Wojtyły — Jana Pawła II. Trasa prowadzi przez historyczne centrum Wadowic i okoliczne wzgórza. Dystanse: 5 km (rodzinny), 10 km i half marathon 21 km. Impreza o charakterze charytatywnym — dochód przekazywany na cele społeczne.',
  '5 km / 10 km / 21 km',
  'easy',
  3000,
  55,
  'https://biegpapieski.pl',
  '2026-04-12',
  'Fundacja Pamięci Jana Pawła II',
  'bieg@wadowice.pl',
  'https://biegpapieski.pl',
  'published',
  false,
  49.8869,
  19.4980
),

(
  'PZU Maraton Warszawski 2026',
  'pzu-maraton-warszawski-2026',
  'running',
  '2026-09-27',
  '2026-09-27',
  'Warszawa',
  'mazowieckie',
  'Jeden z największych biegów ulicznych w Polsce i Europie Środkowej. Trasa wiedzie przez najpiękniejsze zakątki stolicy — od Starego Miasta przez Łazienki, Wilanów i powrót do Centrum. Certyfikowany przez World Athletics. Limit czasu: 6 godzin. Pakiet startowy: koszulka techniczna, medal finishera, woda i napoje na trasie.',
  '42,195 km',
  'medium',
  15000,
  149,
  'https://maratonwarszawski.com',
  '2026-09-15',
  'Fundacja Warsaw Marathon',
  'info@maratonwarszawski.com',
  'https://maratonwarszawski.com',
  'published',
  true,
  52.2297,
  21.0122
),

(
  'Bieg Piastów Szklarska Poręba 2026',
  'bieg-piastow-szklarska-poreba-2026',
  'running',
  '2026-05-30',
  '2026-05-31',
  'Szklarska Poręba',
  'dolnośląskie',
  'Legendarny bieg narciarski przemieniony na bieg terenowy — po tych samych trasach Izerskich szlaków. Dystanse: 10 km i 30 km w sercu Sudetów. Trasa w większości leśna, z pięknymi widokami na Karkonosze i Góry Izerskie. Rodzinna atmosfera i prawdziwy duch rywalizacji.',
  '10 km / 30 km',
  'medium',
  2000,
  120,
  'https://biegpiastow.pl',
  '2026-05-22',
  'Klub Biegowy Szklarska',
  'bieg@szklarskagoreba.pl',
  'https://biegpiastow.pl',
  'published',
  false,
  50.8260,
  15.5213
),

(
  'Ultra Trail Tatry 2026',
  'ultra-trail-tatry-2026',
  'trail',
  '2026-08-28',
  '2026-08-30',
  'Zakopane',
  'małopolskie',
  'Najtrudniejszy ultra trail w Polsce — 100 km przez Tatry z przewyższeniem 6500 m. Trasa biegnie przez najwyższe partie Tatr Wysokich, przez Rysy, Świnicę i Kasprowy Wierch. Limit czasu: 36 godzin. Wymagane doświadczenie w bieganiu górskim. Punkty kontrolne co 10 km z punkacją żywnościową.',
  '100 km D+ 6500m',
  'extreme',
  500,
  350,
  'https://ultratrailtatry.pl',
  '2026-08-01',
  'Polish Ultra Trail Association',
  'start@ultratrailtatry.pl',
  'https://ultratrailtatry.pl',
  'published',
  true,
  49.2992,
  19.9496
),

(
  'Bieg Rzeźnika Karkonosze 2026',
  'bieg-rzeznika-karkonosze-2026',
  'trail',
  '2026-06-06',
  '2026-06-07',
  'Karpacz',
  'dolnośląskie',
  'Kultowy bieg górski w Karkonoszach z widokami na Czechy i Niemcy. Dystanse: 25 km, 50 km i 100 km. Trasa biegnie przez Śnieżkę (1603 m n.p.m.) — najwyższy szczyt Sudetów. Atmosfera biegów górskich sprzed lat: bez komercji, z prawdziwą pasją.',
  '25 km / 50 km / 100 km',
  'hard',
  1200,
  110,
  'https://biegrzeznika.pl',
  '2026-05-25',
  'Stowarzyszenie Biegów Górskich Karkonosze',
  'info@biegrzeznika.pl',
  'https://biegrzeznika.pl',
  'published',
  false,
  50.7681,
  15.7477
),

(
  'Spartan Race Poland — Super Łódź 2026',
  'spartan-race-super-lodz-2026',
  'ocr',
  '2026-05-23',
  '2026-05-24',
  'Łódź',
  'łódzkie',
  'Spartan Race Super — 13 km, 25+ przeszkód. Jedna z najtrudniejszych serii biegów z przeszkodami na świecie przyjeżdża do Łodzi! Wspinaczki, dźwiganie ciężarów, drut kolczasty i słynne 30 karnych burpees za każdą nieukończoną przeszkodę. Czy masz Spartan Spirit?',
  '13 km / 25+ przeszkód',
  'extreme',
  3000,
  249,
  'https://spartanrace.pl',
  '2026-05-16',
  'Spartan Race Poland',
  'poland@spartan.com',
  'https://spartanrace.pl',
  'published',
  false,
  51.7592,
  19.4560
),

(
  'Mazury MTB Challenge 2026',
  'mazury-mtb-challenge-2026',
  'cycling',
  '2026-07-11',
  '2026-07-12',
  'Giżycko',
  'warmińsko-mazurskie',
  'Wyścig MTB przez Krainę Tysiąca Jezior — 80 km tras leśnych z możliwością jazdy po plażach jezior mazurskich. Trzy dystanse: 25 km (rekreacyjny), 50 km (sportowy) i 80 km (zaawansowany). Przeprawa promem przez Jezioro Niegocin jako unikalna atrakcja trasy. Miasteczko zawodów w centrum Giżycka.',
  '25 km / 50 km / 80 km',
  'medium',
  800,
  85,
  'https://mazurymtb.pl',
  '2026-07-01',
  'Mazurskie Towarzystwo Kolarskie',
  'kontakt@mazurymtb.pl',
  'https://mazurymtb.pl',
  'published',
  false,
  54.0373,
  21.7686
),

(
  'Bieszczady Gravel Race 2026',
  'bieszczady-gravel-race-2026',
  'cycling',
  '2026-09-05',
  '2026-09-06',
  'Lesko',
  'podkarpackie',
  'Gravel race przez najdziksze zakątki Bieszczad — 160 km tras szutrowych przez Bieszczadzki Park Narodowy. Minimalna obsługa, maksymalna przygoda — styl bikepacking. Jeden z najtrudniejszych gravel events w Polsce z ponad 3000 m przewyższenia. Nocny biwak przy szlaku wliczony w cenę startu.',
  '80 km / 160 km D+ 1500–3000m',
  'medium',
  600,
  79,
  'https://bieszczadygravel.pl',
  '2026-08-25',
  'Podkarpacki Klub Kolarzy Szutrowych',
  'info@bieszczadygravel.pl',
  'https://bieszczadygravel.pl',
  'published',
  false,
  49.4694,
  22.3308
);
